// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package database

import (
	"context"
)

type Querier interface {
	CreateUser(ctx context.Context, arg CreateUserParams) (User, error)
	//
	GetUser(ctx context.Context, apiKey string) (User, error)
}

var _ Querier = (*Queries)(nil)
